### ISSUE TITLE
apssh doesn't kill remote jobs when exiting

### ISSUE THREAD

**Issue by jonglezb** [parmentelat/apssh#7] opened 2018-04-05 13:33 UTC
When `apssh` crashes or is killed, it does not kill remote processes.

A common trick to ensure this is to force pseudo-TTY allocation, with `ssh -tt`.  But it might have side-effects...

**Comment by jonglezb** [comment] 2018-04-05 13:51
This issue also happens when running a SshJob with `forever=True`: the remote process is not killed when apssh exists after all other jobs are finished.

**Comment by parmentelat** [comment] 2018-04-06 07:01
That's bad indeed.

The thing is the whole model is about maximizing the scope onf one ssh connection, so a typical usage - like in the R2lab tutorials - never explicitly tears down an ssh connection, and that typically happens when your experiment script process (the python process that runs your nepi-ng script) exits.

So I would need you to be more explicit: at which point are you exactly when you see the remote process still up ?  for example if you run in a notebook and do s.run(), and it fails, then the ssh connection is still up, it's kind of the expected behaviour

Maybe what we are talking about is more examples in the documentation about how to handle that more cleanly ?

**Comment by jonglezb** [comment] 2018-04-09 09:11
In this case, I was running nepi-ng in a python script, and the remote process lingered even after my script exited.

To reproduce, run this in a script:

```
from asynciojobs import Scheduler
from apssh import SshJob, SshNode, Run, RunString

s = Scheduler()

gw = SshNode('faraday.inria.fr', username='inria_school')
node = SshNode('fit01', username='root', gateway=gw)

foreverjob = SshJob(node=node, command=Run("sleep 7200"),
                    scheduler=s, forever=True)
shortjob = SshJob(node=node, command=Run("sleep 10"),
                  scheduler=s)

s.run()
```
The script will run for 10 seconds (`shortjob`) and then exit.

Then connect to `fit01`, and see that the long-running process (`foreverjob`) is still running on the node:

```
root@fit01:~# ps aux | grep sleep
root      2544  0.0  0.0   4384   652 ?        S    11:04   0:00 sleep 7200
```
This process is a child of PID 1 on the node, it is no longer tied to any SSH session.

**Comment by parmentelat** [comment] 2018-04-09 11:06
OK, yes, you're right, I confirm that I can reproduce this behaviour

I had failed to notice the lingering process because as you pointed out it gets attached to pid 1

that's a pretty serious issue, I'll dig into this shortly, thanks for spotting that !

for the record here's the monitoring command that I run on the node 

    while true; do echo ==== $(date) ; ps -o pid,ppid,cmd $(pgrep sleep); sleep 2; done

**Comment by jonglezb** [comment] 2018-04-09 11:55
Ok, thanks!

It seems that setting `term_type` is a way to force `asyncssh` to allocate a PTY: see  https://asyncssh.readthedocs.io/en/latest/index.html#setting-terminal-information and https://github.com/ronf/asyncssh/blob/master/asyncssh/channel.py#L1016

There might be a simpler way to properly kill remote processes on disconnection, but I haven't found anything else in the `asyncssh` docs.

**Comment by jonglezb** [comment] 2018-04-09 13:55
Regarding the side-effects of forcing a PTY allocation: it causes stdout and stderr of the remote process to be mixed up.
See https://asyncssh.readthedocs.io/en/latest/index.html#setting-terminal-information

**Comment by parmentelat** [comment] 2018-04-09 14:54
As a quick update on this issue:

There's an interesting discussion of [a similar issue here](https://unix.stackexchange.com/questions/103699/kill-process-spawned-by-ssh-when-ssh-dies)
Turns out that, as your example only uses `sleep` processes on the remote end, there is no I/O involved, and the process can indeed go on.
If you tweak you test to do instead

    command = RunString("for i in $(seq 900); echo $i; sleep 1; done")
    foreverjob = SshJob(node=node,
                        command=command,
                        scheduler=s,
                        forever=True)

then the process dies as expected;

Of course, I am not suggesting this is a workarounf, it is just to explain why I had never observed that behaviour before :)

Now; I don't wish to mess with term_type, that would be very wrong IMHO; if only because, IIUC that would result in stdout and stderr to be mixed in, and we don't want that;

`asyncssh` does indeed expose methods like `kill` and `terminate` on its `SshClientChannel` class, but I have not yet been able to get this to do what I want. 

to be continued then..

**Comment by jonglezb** [comment] 2018-04-09 15:16
> There's an interesting discussion of a similar issue here
> Turns out that, as your example only uses sleep processes on the remote end, there is no I/O involved, and the process can indeed go on.

Ah right, my original code was spawning an iperf server (`iperf -s`), which does not output anything while it is waiting for clients to connect.

**Comment by parmentelat** [comment] 2018-04-10 13:53
see also ronf/asyncssh#135

**Comment by parmentelat** [comment] 2018-04-11 09:55
as a follow up on this, after I've read Ron's description (that the openssh server does not implement signal sending) I would be in favour of keeping quiet until the issue is fixed upstream

to that end I suggest that you add your own support for the feature request on this thread, it can't hurt:
https://bugzilla.mindrot.org/show_bug.cgi?id=1424

As I said, until this is fixed in openssh, the situation we're in here is that
* the issue only affects processes that don't do IO's on stdout, which already makes it way less severe
* the changes in apssh for this to behave properly are going to be a little tricky
* and so the last thing I need is the need for additional workarounds in order for these changes to trigger with the current openssh servers.

so honestly my feeling is we're better off with the simple, and reasonably robust code that we have now, rather than a very convoluted one, that I am not certain will fix a rather mundane issue

of course I'm ready to discuss this, particularly if you feel like I underestimate the seriousness of this bug in use cases that I would have overlooked

**Comment by jonglezb** [comment] 2018-04-11 13:56
Thanks for finding this!  Indeed, it seems there is little we can do client-side without hacking, and I can live with this "bug" :)

For the record, [here is a wrapper script](https://gist.github.com/jonglezb/35e3452ae2db59cdc6788454c03e365f) that can be used to work-around this issue.  It basically starts the desired command, watches the parent process (sshd), and kills the command whenever the parent process disappears.  I'm not suggesting to integrate this hack into apssh but it may be useful...

**Comment by parmentelat** [comment] 2018-04-12 12:09
interesting, thanks

the r2lab-embedded repo is designed as a small set of swiss knife utilities that ship on faraday and the nodes

if you are fine with that idea, I may consider adding this into our r2lab stack, somewhere around 
https://github.com/fit-r2lab/r2lab-embedded/tree/master/shell

what do you think ?

**Comment by parmentelat** [comment] 2022-11-04 13:50
as an update, a lot of water has passed under the bridge
upstream openssh has implemented this much needed feature as described in 
https://github.com/ronf/asyncssh/issues/112#issuecomment-1289797218
and so we are out of the woods as well

so, closing this at last

**Closed as completed by parmentelat** 2022-11-04 13:50 UTC
